### ISSUE TITLE
requires extra modules with macports version of python3

### ISSUE THREAD

**Issue by raybellis** [kirei/dnssec-ta-tools#12]
On MacOS 10.11.6 with macports and python34 @3.4.5 there are some additional dependencies for `dnssec_ta_tool.py` that aren't auto installed and perhaps should be documented:

- `py34-iso8601`
- `py34-xmltodict`
- `py34-dnspython`

**Comment by paulehoffman** [comment]
Welcome to library hell!

**Comment by jschlyter** [comment]
All requirements are now documented in `requirements.txt` as well as setup.py. They are installed automatically when using pip (e.g., egg/wheel) and when setting up virtual environments using the Makefiles.
